name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 0.4.1
homepage: https://github.com/jg-l/metadata_fetch

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http: ^1.1.0 #https://pub.dev/packages/http
  string_validator: ^1.0.0 #https://pub.dev/packages/string_validator
  html: ^0.15.4 #https://pub.dev/packages/html

dev_dependencies:
  pedantic: ^1.11.1 #https://pub.dev/packages/pedantic
  test: ^1.24.6 #https://pub.dev/packages/test
